env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-recommended
  - eslint:recommended
  - standard-with-typescript
  - plugin:@vue/prettier
  - plugin:@typescript-eslint/recommended
  # - plugin:vue/vue3-essential
parser: plugin:@typescript-eslint/parser
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {}
